name: Binary Compatibility

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v2.6.*

jobs:
  check-binary-compatibility:
    name: Check / Binary Compatibility
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # The versions of scala specified here are only used as `-Dakka.build.scalaVersion=...`
        # which ignores the PATCH portion of the version id. These Scala versions don't need
        # to be fully defined here then since Akka build handles which patch version will be used.
        scalaVersion: [ "2.12", "2.13" ]
    steps:
      - name: Base setup
        uses: ignasi35/akka-base-action@v1
        with:
          olafurpg-java-version: 'adopt@1.8.0'
      - name: Report MiMa Binary Issues
        run: sbt -jvm-opts .jvmopts-ci -Dakka.build.scalaVersion=${{ matrix.scalaVersion }} mimaReportBinaryIssues
