name: Pull Requests

on:
  pull_request:

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-code-style:
    name: Check / Code Style
    runs-on: ubuntu-20.04
    steps:
      - name: Base setup
        uses: ignasi35/akka-base-action@v1
        with:
          olafurpg-java-version: 'adopt@1.8.0'

## https://github.com/akka/akka/issues/30459
#    ghtag "$ghprbPullId" akka akka '["validating"]' "tested needs-attention"

      - name: Code style check
        run: |-
          sbt -jvm-opts .jvmopts-ci \
          -Dsbt.override.build.repos=false \
          -Dsbt.log.noformat=false \
          scalafmtCheckAll scalafmtSbtCheck headerCheckAll

  check-publish:
    name: Check / Publish Local
    runs-on: ubuntu-20.04
    steps:
      - name: Base setup
        uses: ignasi35/akka-base-action@v1
        with:
          olafurpg-java-version: 'adopt@1.8.0'

      - name: Akka publishLocal
        run: |-
          sbt -jvm-opts .jvmopts-ci \
          -Dsbt.override.build.repos=false \
          -Dsbt.log.noformat=false \
          publishLocal publishM2


  pull-request-validation:
    name: Check / Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Base setup
        uses: ignasi35/akka-base-action@v1
        with:
          olafurpg-java-version: 'adopt@1.8.0'

      - name: sbt validatePullRequest
        run: |-
          sbt -jvm-opts .jvmopts-ci \
          -Dakka.mima.enabled=false \
          -Dakka.ci-server=true \
          -Dakka.test.multi-in-test=false \
          -Dakka.test.timefactor=2 \
          -Dakka.cluster.assert=on \
          -Dsbt.override.build.repos=false \
          -Dakka.test.multi-node=false \
          -Dsbt.log.noformat=false \
          -Dakka.log.timestamps=true \
          validateCompile validatePullRequest

## https://github.com/akka/akka/issues/30459
## if success
#    ghtag "$ghprbPullId" akka akka '["tested"]' "validating needs-attention"
## if aborted or unstable
#    ghtag "$ghprbPullId" akka akka '["needs-attention"]' "tested validating"
