name: Akka Strem Perf Spec

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test
    runs-on: self-hosted
    if: github.repository == 'akka/akka'

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.2

      - name: Run Performance tests
        run: |
          cp .jvmopts-perf-ci .jvmopts
          sbt \
            -Dakka.ci-server=true \
            -Dakka.test.timefactor=1 \
            -Djava.security.egd=file:/dev/./urandom \
            -Dakka.test.timefactor=1 \
            "akka-bench-jmh/jmh:compile" \
            "akka-bench-jmh/jmh:runMain akka.BenchRunner full -rf csv -rff GraphBuilderBenchmark.csv -p complexity=10 akka.stream.GraphBuilderBenchmark" \
            "akka-bench-jmh/jmh:runMain akka.BenchRunner full -rf csv -rff MaterializationBenchmark.csv -p complexity=10 akka.stream.MaterializationBenchmark"

      - name: 'Store produced csv files'
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results ${{ matrix.command }}
          path: akka-bench-jmh/*.csv
          if-no-files-found: error
