name: Publish

on:
  push:
    branches:
      - master
      # for testing the GH Action without merging to master,
      # in some cases
      - test-publish-snapshots
    tags: ["*"]

jobs:
  sbt:
    name: sbt publish
    runs-on: ubuntu-20.04
    steps:
      - name: Base setup
        uses: ignasi35/akka-base-action@v1
        with:
          olafurpg-java-version: 'adopt@1.11.0-9'

      - name: Publish
        run: |-
          sudo apt-get install graphviz
          sbt +mimaReportBinaryIssues
          sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
